const ALERT = 'ALERT';
const REFETCH_CHAT = 'REFETCH_CHAT';
const NEW_ATTACHMENT = "NEW_ATTACHMENTS";
const NEW_ATTACHMENT_ALERT = "NEW_MESSAGE_ALERT";

export { ALERT, REFETCH_CHAT, NEW_ATTACHMENT, NEW_ATTACHMENT_ALERT }